#!/bin/bash
# ============================================================================
# BTC ML Production - pgAdmin4 Entrypoint Script
# Configures pgAdmin for Docker environment with auto-db connection
# ============================================================================

set -e  # Exit on any error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  # No Color

# Log functions with color
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Initialization
log_info "=========================================="
log_info "pgAdmin4 - Bitcoin ML Production Setup"
log_info "=========================================="

# Create required directories
log_info "Creating pgAdmin directories..."
mkdir -p /var/lib/pgadmin
mkdir -p /var/log/pgadmin
mkdir -p /var/lib/pgadmin/.postgresql

# Set proper permissions
log_info "Setting directory permissions..."
chown -R pgadmin:pgadmin /var/lib/pgadmin
chown -R pgadmin:pgadmin /var/log/pgadmin
chmod 700 /var/lib/pgadmin
chmod 700 /var/log/pgadmin

# Validate required environment variables
log_info "Validating environment variables..."

if [ -z "$DB_PASSWORD" ]; then
    log_error "DB_PASSWORD not set! Required for pgpass file."
    exit 1
fi

if [ -z "$PGADMIN_DEFAULT_EMAIL" ]; then
    log_error "PGADMIN_DEFAULT_EMAIL not set!"
    exit 1
fi

if [ -z "$PGADMIN_DEFAULT_PASSWORD" ]; then
    log_error "PGADMIN_DEFAULT_PASSWORD not set!"
    exit 1
fi

log_info "Environment variables validated ✓"

# Create pgpass file from environment variable
log_info "Creating pgpass file..."
cat > /var/lib/pgadmin/pgpass << EOF
# Autogenerated by entrypoint.sh - $(date -u +%Y-%m-%dT%H:%M:%SZ)
timescaledb:5432:btc_ml_production:mltrader:${DB_PASSWORD}
EOF

# Set strict permissions on pgpass (600 = rw-------)
chmod 600 /var/lib/pgadmin/pgpass
chown pgadmin:pgadmin /var/lib/pgadmin/pgpass

log_info "pgpass file created with secure permissions (600) ✓"

# Copy servers.json if not exists (allows user to provide custom)
if [ ! -f /var/lib/pgadmin/servers.json ]; then
    log_info "Copying default servers.json..."
    if [ -f /servers.json ]; then
        cp /servers.json /var/lib/pgadmin/servers.json
        chown pgadmin:pgadmin /var/lib/pgadmin/servers.json
        chmod 644 /var/lib/pgadmin/servers.json
        log_info "servers.json copied ✓"
    else
        log_warn "No servers.json found in /servers.json - skipping"
    fi
else
    log_info "servers.json already exists - skipping"
fi

# Create postgresql client config for connection timeouts
log_info "Creating PostgreSQL client configuration..."
cat > /var/lib/pgadmin/.postgresql/postgresql.conf << EOF
# PostgreSQL client configuration for pgAdmin
# Created by entrypoint.sh

# Connection timeout (seconds)
# timeout = 10

# Statement timeout (milliseconds)
# statement_timeout = 30000
EOF

chown pgadmin:pgadmin /var/lib/pgadmin/.postgresql/postgresql.conf
chmod 600 /var/lib/pgadmin/.postgresql/postgresql.conf

# Set pgAdmin configuration environment variables
log_info "Setting pgAdmin configuration..."

export SCRIPT_NAME=/pgadmin4
export PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
export PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
export PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
export PGADMIN_CONFIG_ENHANCED_SQL_EDITOR=True
export PGADMIN_CONFIG_DISPLAY_COMMENTS=True
export PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
export SCRIPT_NAME=/pgadmin4

log_info "pgAdmin configuration set ✓"

# Display startup information
log_info "=========================================="
log_info "pgAdmin4 Configuration Complete"
log_info "=========================================="
log_info "Service Port: 8000"
log_info "Admin Email: ${PGADMIN_DEFAULT_EMAIL}"
log_info "Database Host: timescaledb"
log_info "Database: btc_ml_production"
log_info "Database User: mltrader"
log_info "Auto-connect: Enabled"
log_info "=========================================="
log_info ""
log_info "Starting pgAdmin4..."
log_info ""

# Execute the original pgAdmin entrypoint
# This script replaces the default entrypoint
exec /entrypoint.sh "$@"
